### ISSUE TITLE
Error: package 'worlds_project' not found

### ISSUE THREAD

**Issue by ArghyaChatterjee** [jtorde/planning_worlds_gazebo#1]
Hello sir,
I was trying to run your project on my Ubuntu 16.04 OS running ROS Kinetic when I found the error.

`arghya@arghya-Aspire-VN7-571G:~/catkin_ws$ rosrun worlds_project create_random_forest
[rospack] Error: package 'worlds_project' not found`

I have installed the package the way you mentioned in the Readme section.  

There is also another question. Do I need to launch the start_world.launch first and then launch empty_world.launch and then trigger the rosrun command or The first one is a separate command and the second + third one combinedly another separate command.
Thanks.

**Comment by jtorde** [comment]
Hi!

1) 
You're right, there was a typo in the Readme, it should be `planning_worlds_gazebo` instead of `worlds_project` (I've just updated the Readme, thanks)

2) 
If you want to use one of the worlds that come with this package, running 
`roslaunch planning_worlds_gazebo start_world.launch`
is enough (you can change the name of the world you want to launch in the file `.launch`)

If you want to create another random forest different from the ones provided, then you have to run:

- In one terminal `roslaunch gazebo_ros empty_world.launch`
- In a different one `rosrun planning_worlds_gazebo create_random_forest`

(remember to do `source devel/setup.bash` whenever you open a new terminal, or put it in your `~/.bashrc`)

I'm closing this for now, but let me know if you have any problems!
